apiVersion : "apps/v1"
kind : Deployment
metadata:
  name : java-deployment
  labels:
    app : java
spec:
  template :
    metadata:
      labels :
        app : java
    spec:
      containers:
        - name : java
          image : devtechieops/java:3.0
          ports:
            - containerPort : 8080
  selector:
    matchLabels:
      app : java

