apiVersion : apps/v1
kind: Deployment
metadata:
  name : form-deployment
  labels:
    app: tomcat

spec:
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name : tomcat
          image : devtechieops/form:1.0
          ports:
            - containerPort : 8080
  selector:
    matchLabels:
      app: tomcat

                 
